apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    operator-deployment: prober
  name: operator
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      operator: prober
  template:
    metadata:
      labels:
        operator: prober
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: webhook-config
        image: operator
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 1
        name: operator
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 5001
          name: https
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10000
          runAsGroup: 10000
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - mountPath: /certs
          name: certificates
          readOnly: true
      initContainers:
      - args:
        - webhooks
        - install
        - --replace-existing
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: operator
        name: webhook-installer
        volumeMounts:
        - mountPath: /certs
          name: certificates
        - mountPath: /ca
          name: ca-certificates
          readOnly: true
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 10000
          runAsGroup: 10000
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: certificates
      - configMap:
          name: webhook-ca
        name: ca-certificates