apiVersion: d-teknoloji.com.tr/v1alpha1
kind: Probe
metadata:
  name: rabbitmq-probe
  namespace: rabbitmq-app
  labels:
    app: beta-app
spec:
  period: 1m
  description: rabbitmq probe
  type: RabbitMq
  parameters: |
    connectionString: "amqp://localhost:5672"
