apiVersion: d-teknoloji.com.tr/v1alpha1
kind: Probe
metadata:
  name: request-size-probe
  labels:
    app: alpha-app
spec:
  period: 3s
  description: Request size probe
  type: UriRequestSize
  parameters: |
    uri: https://d-teknoloji.com.tr
    httpMethod: GET
    httpCode: 200
    requestSize: 1k