namespace: prober-system
namePrefix: prober-
commonLabels:
  operator: prober
resources:
- ./namespace.yaml
- ../crds
- ../rbac
- ../operator
images:
- name: operator
  newName: quay.io/dines/prober
  newTag: e039a4f
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization