apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: probes.d-teknoloji.com.tr
spec:
  group: d-teknoloji.com.tr
  names:
    kind: Probe
    listKind: ProbeList
    plural: probes
    singular: probe
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.status
      name: Probe status
      priority: 0
      type: string
    - jsonPath: .spec.type
      name: Probe type
      priority: 0
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          status:
            properties:
              status:
                type: string
            type: object
          spec:
            properties:
              description:
                type: string
              period:
                type: string
              timeout:
                type: string
              type:
                enum:
                  - RabbitMq
                - Postgresql
                - DnsResolve
                  - UriRequestSize
                type: string
              parameters:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}